import { EventEmitter } from '@angular/core';
export declare class MonthPickerComponent {
    private static readonly TAG;
    private now;
    private months;
    private yearMeta;
    private currentMeta;
    private availableColors;
    expanded: boolean;
    expandedChange: EventEmitter<boolean>;
    currentYear: number;
    currentYearChange: EventEmitter<number>;
    prevYearBtnTap: EventEmitter<{}>;
    nextYearBtnTap: EventEmitter<{}>;
    select: EventEmitter<string>;
    deselect: EventEmitter<string>;
    colors: string[];
    tabindex: number;
    monthsPerRow: number;
    useShortNames: boolean;
    useAvailableMonths: boolean;
    expandable: boolean;
    prevYearAvailable: boolean;
    nextYearAvailable: boolean;
    maxYear: number;
    closeBtnIcon: string;
    prevYearBtnIcon: string;
    nextYearBtnIcon: string;
    maxSelectableItems: number;
    minSelectableItems: number;
    ngOnInit(): void;
    private setYearMeta(year);
    private createYearMeta(year);
    selectMonth(month: number, year?: number): void;
    isMonthAvailable(month: number, year: number): boolean;
    isDateInBounds(month: number, year: number): boolean;
    isMonthInBounds(month: number): boolean;
    isYearInBounds(year: number): boolean;
    private getYearMeta(year);
    private iterateMonthMetas(cb);
    getSelectedDates(): string[];
    private setMonthBackgroundColor(month, year);
    private getMonthBackgroundColor();
    deselectMonth(month: number, year?: number): void;
    isMonthSelected(month: number, year: number): boolean;
    private clearMonthBackgroundColor(month, year);
    deselectAllMonths(): void;
    addAvailableMonth(month: number, year: number): void;
    removeAvailableMonth(month: number, year: number): void;
    removeAllAvailableMonths(): void;
    private onPrevYearTap();
    private onNextYearTap();
    private onCloseBtnTap();
    private notifySelect(date);
    private notifyDeselect(date);
    isCurrentMonth(month: number, year?: number): boolean;
    getMonth(year: number, month: number): any;
    static readonly monthNames: string[];
    static readonly monthNamesShort: string[];
}
