language: node_js
node_js:
  - "8.11"

branches:
  only:
  - dev
  - master

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

script:
  - npm install
  - npm run docs:$TRAVIS_BRANCH
  - npm run docs:deploy
