language: node_js
node_js:
  - "8.11"

branches:
  only:
  - dev

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

script:
  - npm install
  - npm run docs:dev
  - npm run docs:deploy
