language: node_js
node_js:
  - "12"

branches:
  only:
  - dev
  - master
  - v0.8

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

script:
  - npm install
  - npm run docs
  - npm run docs:deploy
